version: "3"
services:
    bot-1:
      restart: "no"
      shm_size: 4000m
      build:
        dockerfile: Dockerfile
        context: .
      volumes:
        - ./output:/app/output
        - ./tasks:/app/tasks
        - ./profiles:/app/profiles
        - ./profiles.json:/app/profiles.json
        - ./local_storage.json:/app/local_storage.json